### ISSUE TITLE
LINE 로그인 실패 관련 문의 드립니다.

### ISSUE THREAD

**Issue by mooseung-lee** [itsbio/gamepot-docs#1]
안녕하세요.
아래와 같은 환경 및 설정을 하고 iOS에서 빌드 후 기기에서 실행하면 LINE 로그인 시도시 오류 메시지가 표시되고 로그인이 되지 않습니다.

1. 환경
Unity3D : 2020.3.2f1
GamePot SDK : v3.4.0
Build : iOS Xcode 13.0

2. 설정
 2-1. GamePotConfig-Info.plist
 - gamepot_line_channelid, gamepot_line_url_schemes 모두 셋팅

 2-2. Plugins/IOS/etcFrameworks/GamePotLine.framework 를 Plugins/IOS/Frameworks으로 복사.

 2-3. XCode에서 info.plist 안에 URL types > Item > URL Schemes에 gamepot_line_url_schemes 값이 복사되어 있는 것 확인.

3. 에러
 - **Please check if you have set the "LINE" channel before using it. Did you import or set "LINE" information in info.plist file?**
 - 에러는 게임 진입 후 LINE 로그인 버튼을 누르면 화면 하단에 토스트 메시지로 표시 됩니다.
 - XCode에서는 어떤 로그도 표시 되지 않습니다.

설명서의 모든 셋팅을 했는데 안드로이드는 정상 작동하나 iOS에서는 Apple 로그인 및 GameCenter 로그인은 잘 되나 LINE 로그인만 위와 같은 상황으로 로그인 되지 않습니다.

도움이 필요하여 문의 드립니다.

**Comment by jyj1127j** [comment]
이미 해결했을수도 있습니다만  설명을 드리면 하기 라이브러리도 빌드시 포함되어야 합니다.
LineSDKObjC.framework
LineSDK.framework

위 파일에는 i386 x86_64 아키택처가 있다보니 Xcode에서 빌드가 안되실것입니다. 
해당 파일이 있는 위치로 이동하여 아래와 같이 명령어를 진행하시어 아키택처를 삭제 후 빌드 진행 부탁드립니다.

lipo -remove x86_64 ./LineSDK.framework/LineSDK -o ./LineSDK.framework/LineSDK
lipo -remove i386 ./LineSDK.framework/LineSDK -o ./LineSDK.framework/LineSDK
lipo -remove x86_64 ./LineSDKObjC.framework/LineSDKObjC -o ./LineSDKObjC.framework/LineSDKObjC
lipo -remove i386 ./LineSDKObjC.framework/LineSDKObjC -o ./LineSDKObjC.framework/LineSDKObjC

혹시나 해결이 안되셨다면 네이버 클라우드 문의 채널을 통해 문의를 해주셨으면 합니다.
